### ISSUE TITLE
It didn't work 

### ISSUE THREAD

**Issue by ghost** [paichiwo/pygame-games#1]
Hello I'm still really new in this github stuff so idk how people usually do this. anyway, so I'm going straight to the point.

so i found this game that you have made and i want to try it but it didn't work. even after i have install the requirements it still not work. the codes run when i try to run it however, after that it stop and the terminal give me this. so i don't know what should i do here
![Screenshot 2024-06-29 221118](https://github.com/paichiwo/space_resistance_game/assets/126782053/c5296fbb-7916-4e5b-a2a3-7de44adeaa5e)

**Comment by paichiwo** [comment]
ok thank you for pointing this out, working version will be out soon and i will notify you

**Comment by paichiwo** [comment]
new version: 
- clone repository: https://github.com/paichiwo/space_resistance_game/
- download: https://github.com/paichiwo/space_resistance_game/releases/tag/v0.4

**Comment by ghost** [comment]
alright its work now. its really nice game your working on, my suggest is to increase the boss difficulty because the fight is too easy if i been honest. and sorry for the late response.
